apiVersion: v1
kind: Service
metadata:
 name: currency-converter-eks-service
spec:
 type: NodePort
 selector:
   app: currency-converter-deployment-eks-service-pod #defined in the deployment
 ports:
 - port: 8081 #where container is actually running
   targetPort: 8081 #port of this service. Cluster members talk via this port
   nodePort: 30123 #external traffic
